version: '3'
services:
  test-container:
    command: tail -f /dev/null
    container_name: test-container
    environment:
      CQL_EXECUTION_DATA_SERVICE: "${CQL_EXECUTION_DATA_SERVICE:-https://apps.hdap.gatech.edu/gt-fhir/fhir/}"
    image: alpine:latest
